#"project_id_env": CROWDIN_PROJECT_ID
#"api_token_env": CROWDIN_PERSONAL_TOKEN

"export_languages": [
  "es", 
  "ca"
]

"preserve_hierarchy": true

files: [
  {
    "source" : "/locales/en/messages.json",
    "translation" : "/locales/%two_letters_code%/%original_file_name%",

    "languages_mapping" : {
      "two_letters_code" : {
        "pt-BR" : "pt_BR",
        "zh-CN" : "zh_CN",
        "zh-TW" : "zh_TW"
      }
    }
  }
]
