name: PR

on:
  pull_request:
    branches:
      - hide_artifact_links
      - master
      - '*-maintenance'

env:
  comment_prefix: "Do you want to test this code? Here you have an automated build:"
  comment_suffix: "WARNING: It may be unstable and result in corrupted configurations or data loss. Use only for testing!"

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  hide-artifact-links:
    name: Hide/add artifact links to PR comments
    needs: ci
    runs-on: ubuntu-20.04
    steps:
      - name: Hide old comments with artifact links
        uses: int128/hide-comment-action@v1
        with:
          starts-with: ${{ env.comment_prefix }}
          ends-with: ${{ env.comment_suffix }}
      
      - name: Add comment with new artifact links
        uses: ./.github/actions/artifact-links
        with:
          comment_prefix: ${{ env.comment_prefix }}
          comment_suffix: ${{ env.comment_suffix }}
