name: Translations PR

on: workflow_dispatch

jobs:
  crowdin-translations-to-pr:
    name: Create a PR with the latest translations from Crowdin
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Download Crowdin translations and create PR
      uses: crowdin/github-action@1.5.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

        upload_sources: false
        upload_translations: false

        crowdin_branch_name: master
        #source: locales/en/messages.json
        #translation: locales/%two_letters_code%/%original_file_name%

        download_translations: true
        localization_branch_name: update_translations_crowdin
        push_translations: true
        commit_message: 'Update translations'

        create_pull_request: true
        pull_request_title: 'Update translations'
        pull_request_body: >
          This is an automated build.

          This PR updates the translations using the content from Crowdin. Thanks to all the translators for the really hard work!!!

          If you want to help to make the localization better, or add a new language, go to [Crowdin](https://crowdin.com/project/betaflight-configurator) and start helping!.

          [![Crowdin](https://d322cqt584bo4o.cloudfront.net/betaflight-configurator/localized.svg)](https://crowdin.com/project/betaflight-configurator)
        #pull_request_base_branch_name: master

        config: 'crowdin.yml'
        #dryrun_action: true


